### ISSUE TITLE
Server cannot be stopped.

### ISSUE THREAD

**Issue by skhdl** [vic64/nlpcraft#101]
thread dump below:

"Thread-12" #121 prio=5 os_prio=31 tid=0x00007f9ea74a2000 nid=0xe903 in Object.wait() [0x0000700012142000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1249)
	- locked <0x0000000759cdad38> (a org.nlpcraft.common.util.NCUtils$$anon$4)
	at java.lang.Thread.join(Thread.java:1323)
	at org.nlpcraft.common.util.NCUtils$.stopThread(NCUtils.scala:1168)
	at org.nlpcraft.server.endpoints.NCEndpointManager$.stop(NCEndpointManager.scala:466)
	at org.nlpcraft.server.NCServer$$anonfun$org$nlpcraft$server$NCServer$$stopManagers$1.apply(NCServer.scala:177)
	at org.nlpcraft.server.NCServer$$anonfun$org$nlpcraft$server$NCServer$$stopManagers$1.apply(NCServer.scala:175)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.nlpcraft.server.NCServer$.org$nlpcraft$server$NCServer$$stopManagers(NCServer.scala:175)
	at org.nlpcraft.server.NCServer$$anon$2$$anonfun$run$1.apply$mcV$sp(NCServer.scala:231)
	at org.nlpcraft.server.NCServer$$anon$2$$anonfun$run$1.apply(NCServer.scala:231)
	at org.nlpcraft.server.NCServer$$anon$2$$anonfun$run$1.apply(NCServer.scala:231)
	at scala.util.control.Exception$Catch.apply(Exception.scala:103)
	at org.nlpcraft.server.NCServer$$anon$2.run(NCServer.scala:230)

"SIGINT handler" #125 daemon prio=9 os_prio=31 tid=0x00007f9ea3f97800 nid=0xf0b in Object.wait() [0x000070000f9cd000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1249)
	- locked <0x00000007694577a0> (a org.nlpcraft.server.NCServer$$anon$2)
	at java.lang.Thread.join(Thread.java:1323)
	at java.lang.ApplicationShutdownHooks.runHooks(ApplicationShutdownHooks.java:106)
	at java.lang.ApplicationShutdownHooks$1.run(ApplicationShutdownHooks.java:46)
	at java.lang.Shutdown.runHooks(Shutdown.java:123)
	at java.lang.Shutdown.sequence(Shutdown.java:167)
	at java.lang.Shutdown.exit(Shutdown.java:212)
	- locked <0x000000068028f468> (a java.lang.Class for java.lang.Shutdown)
	at java.lang.Terminator$1.handle(Terminator.java:52)
	at sun.misc.Signal$1.run(Signal.java:212)
	at java.lang.Thread.run(Thread.java:745)

"endpoint-sender-thread" #114 prio=5 os_prio=31 tid=0x00007f9ea70c4800 nid=0x11a03 in Object.wait() [0x000070001192a000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.nlpcraft.server.endpoints.NCEndpointManager$$anonfun$start$3.apply(NCEndpointManager.scala:140)
	- locked <0x00000007578b4120> (a java.lang.Object)
	at org.nlpcraft.server.endpoints.NCEndpointManager$$anonfun$start$3.apply(NCEndpointManager.scala:133)
	at org.nlpcraft.common.util.NCUtils$$anon$4.run(NCUtils.scala:946)

"timeout-scanner" #113 daemon prio=5 os_prio=31 tid=0x00007f9ea3522800 nid=0xe103 in Object.wait() [0x0000700011827000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007576e77c0> (a java.util.TaskQueue)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x00000007576e77c0> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"probe-pinger" #112 daemon prio=5 os_prio=31 tid=0x00007f9ea8172000 nid=0xe003 waiting on condition [0x0000700011724000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.nlpcraft.common.util.NCUtils$.sleep(NCUtils.scala:1152)
	at org.nlpcraft.server.probe.NCProbeManager$$anonfun$start$3.apply(NCProbeManager.scala:195)
	at org.nlpcraft.server.probe.NCProbeManager$$anonfun$start$3.apply(NCProbeManager.scala:193)
	at org.nlpcraft.common.util.NCUtils$$anon$4.run(NCUtils.scala:946)

"probe-mgr-uplink" #111 daemon prio=5 os_prio=31 tid=0x00007f9ea8bd1800 nid=0x11d03 runnable [0x0000700011621000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at org.nlpcraft.server.probe.NCProbeManager$$anon$1.body(NCProbeManager.scala:351)
	at org.nlpcraft.server.probe.NCProbeManager$$anon$1.run(NCProbeManager.scala:324)

"probe-mgr-downlink" #110 daemon prio=5 os_prio=31 tid=0x00007f9ea8863800 nid=0xde03 runnable [0x000070001151e000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at org.nlpcraft.server.probe.NCProbeManager$$anon$1.body(NCProbeManager.scala:351)
	at org.nlpcraft.server.probe.NCProbeManager$$anon$1.run(NCProbeManager.scala:324)

"jdbc-request-handler-worker-#72%nlpcraft%" #107 prio=5 os_prio=31 tid=0x00007f9ea7bb6800 nid=0x12103 waiting on condition [0x0000700011215000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000680c98788> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.ignite.internal.processors.odbc.jdbc.JdbcRequestHandlerWorker.body(JdbcRequestHandlerWorker.java:85)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:120)
	at java.lang.Thread.run(Thread.java:745)

"jdbc-request-handler-worker-#70%nlpcraft%" #106 prio=5 os_prio=31 tid=0x00007f9ea74d1800 nid=0x12203 waiting on condition [0x0000700011112000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000680cbec30> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.ignite.internal.processors.odbc.jdbc.JdbcRequestHandlerWorker.body(JdbcRequestHandlerWorker.java:85)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:120)
	at java.lang.Thread.run(Thread.java:745)

"jdbc-request-handler-worker-#71%nlpcraft%" #105 prio=5 os_prio=31 tid=0x00007f9ea74d1000 nid=0x12403 waiting on condition [0x000070001100f000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000680c69558> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.ignite.internal.processors.odbc.jdbc.JdbcRequestHandlerWorker.body(JdbcRequestHandlerWorker.java:85)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:120)
	at java.lang.Thread.run(Thread.java:745)

"jdbc-request-handler-worker-#69%nlpcraft%" #104 prio=5 os_prio=31 tid=0x00007f9ea807e800 nid=0x12603 waiting on condition [0x0000700010f0c000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000680c6b828> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.ignite.internal.processors.odbc.jdbc.JdbcRequestHandlerWorker.body(JdbcRequestHandlerWorker.java:85)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:120)
	at java.lang.Thread.run(Thread.java:745)

"jdbc-request-handler-worker-#64%nlpcraft%" #101 prio=5 os_prio=31 tid=0x00007f9ea7bba800 nid=0xd803 waiting on condition [0x0000700010c03000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000680cc0250> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.ignite.internal.processors.odbc.jdbc.JdbcRequestHandlerWorker.body(JdbcRequestHandlerWorker.java:85)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:120)
	at java.lang.Thread.run(Thread.java:745)

"jdbc-request-handler-worker-#66%nlpcraft%" #100 prio=5 os_prio=31 tid=0x00007f9ea6412800 nid=0x12b03 waiting on condition [0x0000700010b00000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000680c68a48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.ignite.internal.processors.odbc.jdbc.JdbcRequestHandlerWorker.body(JdbcRequestHandlerWorker.java:85)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:120)
	at java.lang.Thread.run(Thread.java:745)

"jdbc-request-handler-worker-#65%nlpcraft%" #99 prio=5 os_prio=31 tid=0x00007f9ea7483800 nid=0xd603 waiting on condition [0x00007000109fd000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000680c97118> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.ignite.internal.processors.odbc.jdbc.JdbcRequestHandlerWorker.body(JdbcRequestHandlerWorker.java:85)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:120)
	at java.lang.Thread.run(Thread.java:745)

"jdbc-request-handler-worker-#59%nlpcraft%" #94 prio=5 os_prio=31 tid=0x00007f9ea80e0000 nid=0xd103 waiting on condition [0x00007000105f1000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000680c97c28> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.ignite.internal.processors.odbc.jdbc.JdbcRequestHandlerWorker.body(JdbcRequestHandlerWorker.java:85)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:120)
	at java.lang.Thread.run(Thread.java:745)

"jdbc-request-handler-worker-#60%nlpcraft%" #95 prio=5 os_prio=31 tid=0x00007f9ea80fb000 nid=0x13003 waiting on condition [0x00007000104ee000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000680cbf740> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.ignite.internal.processors.odbc.jdbc.JdbcRequestHandlerWorker.body(JdbcRequestHandlerWorker.java:85)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:120)
	at java.lang.Thread.run(Thread.java:745)

"jdbc-request-handler-worker-#58%nlpcraft%" #93 prio=5 os_prio=31 tid=0x00007f9ea640f800 nid=0xcf03 waiting on condition [0x00007000103eb000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000680cec2b0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at org.apache.ignite.internal.processors.odbc.jdbc.JdbcRequestHandlerWorker.body(JdbcRequestHandlerWorker.java:85)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:120)
	at java.lang.Thread.run(Thread.java:745)

"C3P0PooledConnectionPoolManager[identityToken->1hgfcb2a4bctqexn16pab|3a82a1ed]-HelperThread-#2" #89 daemon prio=5 os_prio=31 tid=0x00007f9ea7bb9800 nid=0xcc03 in Object.wait() [0x00007000100e2000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:683)
	- locked <0x0000000680de0b28> (a com.mchange.v2.async.ThreadPoolAsynchronousRunner)

"C3P0PooledConnectionPoolManager[identityToken->1hgfcb2a4bctqexn16pab|3a82a1ed]-HelperThread-#1" #88 daemon prio=5 os_prio=31 tid=0x00007f9ea7bbc800 nid=0x13503 in Object.wait() [0x000070000ffdf000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:683)
	- locked <0x0000000680de0b28> (a com.mchange.v2.async.ThreadPoolAsynchronousRunner)

"C3P0PooledConnectionPoolManager[identityToken->1hgfcb2a4bctqexn16pab|3a82a1ed]-HelperThread-#0" #87 daemon prio=5 os_prio=31 tid=0x00007f9ea7ba4000 nid=0x13703 in Object.wait() [0x000070000fedc000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:683)
	- locked <0x0000000680de0b28> (a com.mchange.v2.async.ThreadPoolAsynchronousRunner)

"C3P0PooledConnectionPoolManager[identityToken->1hgfcb2a4bctqexn16pab|3a82a1ed]-AdminTaskTimer" #86 daemon prio=5 os_prio=31 tid=0x00007f9ea7473000 nid=0x13803 in Object.wait() [0x000070000fdd9000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.util.TimerThread.mainLoop(Timer.java:552)
	- locked <0x0000000680de1d68> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"ForkJoinPool-1-worker-1" #83 daemon prio=5 os_prio=31 tid=0x00007f9ea74aa800 nid=0xc903 waiting on condition [0x000070000fbd3000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000681e85d68> (a scala.concurrent.forkjoin.ForkJoinPool)
	at scala.concurrent.forkjoin.ForkJoinPool.scan(ForkJoinPool.java:2075)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

"ForkJoinPool-1-worker-7" #80 daemon prio=5 os_prio=31 tid=0x00007f9ea3367800 nid=0x13c03 waiting on condition [0x000070000f8ca000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000681e85d68> (a scala.concurrent.forkjoin.ForkJoinPool)
	at scala.concurrent.forkjoin.ForkJoinPool.idleAwaitWork(ForkJoinPool.java:2135)
	at scala.concurrent.forkjoin.ForkJoinPool.scan(ForkJoinPool.java:2067)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

"Thread-1" #44 daemon prio=5 os_prio=31 tid=0x00007f9ea2f60800 nid=0x7d03 waiting on condition [0x000070000d561000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006805e8e50> (a java.util.concurrent.SynchronousQueue$TransferStack)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"Attach Listener" #12 daemon prio=9 os_prio=31 tid=0x00007f9ea58e9800 nid=0x5603 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #10 daemon prio=9 os_prio=31 tid=0x00007f9ea299c800 nid=0x4403 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #9 daemon prio=9 os_prio=31 tid=0x00007f9ea588a800 nid=0x4103 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #8 daemon prio=9 os_prio=31 tid=0x00007f9ea3a0b800 nid=0x4003 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #7 daemon prio=9 os_prio=31 tid=0x00007f9ea5881800 nid=0x3e03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=31 tid=0x00007f9ea299b800 nid=0x3c03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Monitor Ctrl-Break" #5 daemon prio=5 os_prio=31 tid=0x00007f9ea2991800 nid=0x3a03 runnable [0x000070000adec000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x000000068001fc18> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <0x000000068001fc18> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at com.intellij.rt.execution.application.AppMainV2$1.run(AppMainV2.java:64)

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007f9ea500e000 nid=0x3903 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007f9ea5802800 nid=0x4c03 in Object.wait() [0x000070000abe6000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000680033940> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x0000000680033940> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007f9ea3819000 nid=0x4d03 in Object.wait() [0x000070000aae3000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x000000068002b960> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x000000068002b960> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=31 tid=0x00007f9ea2805800 nid=0x1903 waiting on condition [0x000070000a0c5000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000683325fc0> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.nlpcraft.server.NCServer$$anonfun$org$nlpcraft$server$NCServer$$start$1.apply$mcV$sp(NCServer.scala:239)
	at org.nlpcraft.common.util.NCUtils$.ignoreInterrupt(NCUtils.scala:261)
	at org.nlpcraft.server.NCServer$.org$nlpcraft$server$NCServer$$start(NCServer.scala:238)
	at org.nlpcraft.server.NCServer$$anonfun$2.apply$mcV$sp(NCServer.scala:249)
	at org.nlpcraft.server.ignite.NCIgniteRunner$.runWith(NCIgniteRunner.scala:98)
	at org.nlpcraft.server.NCServer$.delayedEndpoint$org$nlpcraft$server$NCServer$1(NCServer.scala:244)
	at org.nlpcraft.server.NCServer$delayedInit$body.apply(NCServer.scala:68)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at org.nlpcraft.server.NCServer$.main(NCServer.scala:68)
	at org.nlpcraft.server.NCServer.main(NCServer.scala)

"VM Thread" os_prio=31 tid=0x00007f9ea6006000 nid=0x3103 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007f9ea2806800 nid=0x2007 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007f9ea2807000 nid=0x2a03 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007f9ea2808000 nid=0x2c03 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007f9ea280d800 nid=0x5403 runnable 

"GC task thread#4 (ParallelGC)" os_prio=31 tid=0x00007f9ea280e000 nid=0x5203 runnable 

"GC task thread#5 (ParallelGC)" os_prio=31 tid=0x00007f9ea280e800 nid=0x5103 runnable 

"GC task thread#6 (ParallelGC)" os_prio=31 tid=0x00007f9ea280f000 nid=0x4f03 runnable 

"GC task thread#7 (ParallelGC)" os_prio=31 tid=0x00007f9ea2810000 nid=0x2f03 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007f9ea613e800 nid=0x5503 waiting on condition 

JNI global references: 552

Heap
 PSYoungGen      total 1165312K, used 698565K [0x0000000755580000, 0x00000007c0000000, 0x00000007c0000000)
  eden space 583168K, 76% used [0x0000000755580000,0x0000000770a41708,0x0000000778f00000)
  from space 582144K, 43% used [0x0000000778f00000,0x0000000788470010,0x000000079c780000)
  to   space 582144K, 0% used [0x000000079c780000,0x000000079c780000,0x00000007c0000000)
 ParOldGen       total 3495424K, used 1697054K [0x0000000680000000, 0x0000000755580000, 0x0000000755580000)
  object space 3495424K, 48% used [0x0000000680000000,0x00000006e79478d0,0x0000000755580000)
 Metaspace       used 81492K, capacity 82338K, committed 82736K, reserved 1120256K
  class space    used 10750K, capacity 10954K, committed 11056K, reserved 1048576K

Jul-25 14:40:40 [ERROR] Error during timeout scanner process.
java.lang.IllegalStateException: Grid is in invalid state to perform this operation. It either not started yet or has already being or have stopped [igniteInstanceName=nlpcraft, state=STOPPED]
	at org.apache.ignite.internal.GridKernalGatewayImpl.illegalState(GridKernalGatewayImpl.java:201) ~[ignite-core-2.7.5.jar:2.7.5]
	at org.apache.ignite.internal.GridKernalGatewayImpl.readLock(GridKernalGatewayImpl.java:95) ~[ignite-core-2.7.5.jar:2.7.5]
	at org.apache.ignite.internal.processors.cache.transactions.IgniteTransactionsImpl.txStart0(IgniteTransactionsImpl.java:162) ~[ignite-core-2.7.5.jar:2.7.5]
	at org.apache.ignite.internal.processors.cache.transactions.IgniteTransactionsImpl.txStart(IgniteTransactionsImpl.java:62) ~[ignite-core-2.7.5.jar:2.7.5]
	at org.nlpcraft.server.tx.NCTxManager$$anonfun$startTx$4.apply(NCTxManager.scala:352) ~[classes/:?]
	at scala.util.control.Exception$Catch.apply(Exception.scala:103) ~[scala-library-2.11.12.jar:?]
	at org.nlpcraft.server.tx.NCTxManager$.startTx(NCTxManager.scala:348) ~[classes/:?]
	at org.nlpcraft.server.user.NCUserManager$$anon$1$$anonfun$run$1.apply$mcV$sp(NCUserManager.scala:128) ~[classes/:?]
	at org.nlpcraft.server.user.NCUserManager$$anon$1$$anonfun$run$1.apply(NCUserManager.scala:128) ~[classes/:?]
	at org.nlpcraft.server.user.NCUserManager$$anon$1$$anonfun$run$1.apply(NCUserManager.scala:128) ~[classes/:?]
	at scala.util.control.Exception$Catch.apply(Exception.scala:103) ~[scala-library-2.11.12.jar:?]
	at org.nlpcraft.server.user.NCUserManager$$anon$1.run(NCUserManager.scala:127) [classes/:?]
	at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_121]
	at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_121]
Jul-25 14:41:40 [ERROR] Error during timeout scanner process.
java.lang.IllegalStateException: Grid is in invalid state to perform this operation. It either not started yet or has already being or have stopped [igniteInstanceName=nlpcraft, state=STOPPED]
	at org.apache.ignite.internal.GridKernalGatewayImpl.illegalState(GridKernalGatewayImpl.java:201) ~[ignite-core-2.7.5.jar:2.7.5]
	at org.apache.ignite.internal.GridKernalGatewayImpl.readLock(GridKernalGatewayImpl.java:95) ~[ignite-core-2.7.5.jar:2.7.5]
	at org.apache.ignite.internal.processors.cache.transactions.IgniteTransactionsImpl.txStart0(IgniteTransactionsImpl.java:162) ~[ignite-core-2.7.5.jar:2.7.5]
	at org.apache.ignite.internal.processors.cache.transactions.IgniteTransactionsImpl.txStart(IgniteTransactionsImpl.java:62) ~[ignite-core-2.7.5.jar:2.7.5]
	at org.nlpcraft.server.tx.NCTxManager$$anonfun$startTx$4.apply(NCTxManager.scala:352) ~[classes/:?]
	at scala.util.control.Exception$Catch.apply(Exception.scala:103) ~[scala-library-2.11.12.jar:?]
	at org.nlpcraft.server.tx.NCTxManager$.startTx(NCTxManager.scala:348) ~[classes/:?]
	at org.nlpcraft.server.user.NCUserManager$$anon$1$$anonfun$run$1.apply$mcV$sp(NCUserManager.scala:128) ~[classes/:?]
	at org.nlpcraft.server.user.NCUserManager$$anon$1$$anonfun$run$1.apply(NCUserManager.scala:128) ~[classes/:?]
	at org.nlpcraft.server.user.NCUserManager$$anon$1$$anonfun$run$1.apply(NCUserManager.scala:128) ~[classes/:?]
	at scala.util.control.Exception$Catch.apply(Exception.scala:103) ~[scala-library-2.11.12.jar:?]
	at org.nlpcraft.server.user.NCUserManager$$anon$1.run(NCUserManager.scala:127) [classes/:?]
	at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_121]
	at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_121]

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)

**Comment by vic64** [comment]
Fixed in GH-101 branch.
