### ISSUE TITLE
Strange NPE error while starting REST server

### ISSUE THREAD

**Issue by DankessS** [vic64/nlpcraft#43]
I am using NLPCraft in version 0.5.0. When I run REST server on my local machine all works fine, but when I run it on linux server in docker container then such error apears:

`May-10 12:35:23 [ERROR] Failed to start server due to unexpected error.
java.lang.NullPointerException: null
        at org.nlpcraft.server.user.NCUserManager$.addUser0(NCUserManager.scala:611) ~[nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.user.NCUserManager$$anonfun$start$2.apply$mcV$sp(NCUserManager.scala:173) ~[nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.user.NCUserManager$$anonfun$start$2.apply(NCUserManager.scala:168) ~[nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.user.NCUserManager$$anonfun$start$2.apply(NCUserManager.scala:168) ~[nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.sql.NCSql$$anonfun$sqlEx$1.apply(NCSql.scala:419) ~[nlpcraft-0.5.0.jar:?]
        at scala.util.control.Exception$Catch.apply(Exception.scala:103) ~[scala-library-2.11.12.jar:?]
        at org.nlpcraft.server.sql.NCSql$.sqlEx(NCSql.scala:374) ~[nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.sql.NCSql$.sqlTx(NCSql.scala:341) ~[nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.sql.NCSql$$anonfun$sql$1.apply(NCSql.scala:323) ~[nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.tx.NCTxManager$.org$nlpcraft$server$tx$NCTxManager$$startTx0(NCTxManager.scala:229) ~[nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.tx.NCTxManager$$anonfun$startTx$4.apply(NCTxManager.scala:356) ~[nlpcraft-0.5.0.jar:?]
        at scala.util.control.Exception$Catch.apply(Exception.scala:103) ~[scala-library-2.11.12.jar:?]
        at org.nlpcraft.server.tx.NCTxManager$.startTx(NCTxManager.scala:348) ~[nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.sql.NCSql$.sql(NCSql.scala:322) ~[nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.user.NCUserManager$.start(NCUserManager.scala:167) ~[nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.NCServer$.org$nlpcraft$server$NCServer$$startManagers(NCServer.scala:110) ~[nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.NCServer$$anonfun$1.apply$mcV$sp(NCServer.scala:196) ~[nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.NCServer$$anonfun$1.apply(NCServer.scala:196) ~[nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.NCServer$$anonfun$1.apply(NCServer.scala:196) ~[nlpcraft-0.5.0.jar:?]
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125) ~[scala-library-2.11.12.jar:?]
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125) ~[scala-library-2.11.12.jar:?]
        at scala.util.control.Exception$Catch.apply(Exception.scala:103) ~[scala-library-2.11.12.jar:?]
        at scala.util.control.Exception$Catch.either(Exception.scala:125) ~[scala-library-2.11.12.jar:?]
        at org.nlpcraft.server.NCServer$.org$nlpcraft$server$NCServer$$start(NCServer.scala:196) [nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.NCServer$$anonfun$2.apply$mcV$sp(NCServer.scala:230) [nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.ignite.NCIgniteRunner$.runWith(NCIgniteRunner.scala:98) [nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.NCServer$.delayedEndpoint$org$nlpcraft$server$NCServer$1(NCServer.scala:225) [nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.server.NCServer$delayedInit$body.apply(NCServer.scala:68) [nlpcraft-0.5.0.jar:?]
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34) [scala-library-2.11.12.jar:?]
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12) [scala-library-2.11.12.jar:?]
        at scala.App$$anonfun$main$1.apply(App.scala:76) [scala-library-2.11.12.jar:?]
        at scala.App$$anonfun$main$1.apply(App.scala:76) [scala-library-2.11.12.jar:?]
        at scala.collection.immutable.List.foreach(List.scala:392) [scala-library-2.11.12.jar:?]
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35) [scala-library-2.11.12.jar:?]
        at scala.App$class.main(App.scala:76) [scala-library-2.11.12.jar:?]
        at org.nlpcraft.server.NCServer$.main(NCServer.scala:68) [nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.NCStart$.execute(NCStart.scala:96) [nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.NCStart$.delayedEndpoint$org$nlpcraft$NCStart$1(NCStart.scala:99) [nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.NCStart$delayedInit$body.apply(NCStart.scala:42) [nlpcraft-0.5.0.jar:?]
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34) [scala-library-2.11.12.jar:?]
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12) [scala-library-2.11.12.jar:?]
        at scala.App$$anonfun$main$1.apply(App.scala:76) [scala-library-2.11.12.jar:?]
        at scala.App$$anonfun$main$1.apply(App.scala:76) [scala-library-2.11.12.jar:?]
        at scala.collection.immutable.List.foreach(List.scala:392) [scala-library-2.11.12.jar:?]
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35) [scala-library-2.11.12.jar:?]
        at scala.App$class.main(App.scala:76) [scala-library-2.11.12.jar:?]
        at org.nlpcraft.NCStart$.main(NCStart.scala:42) [nlpcraft-0.5.0.jar:?]
        at org.nlpcraft.NCStart.main(NCStart.scala) [nlpcraft-0.5.0.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282) [exec-maven-plugin-1.6.0.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

I wonder it it is caused by to low resources. On my local machine I have 32GB REM and CPU Intel i7 8850H, so it is rather powerful set, but on linux server there is only 8GB RAM and it is divided into few containers. Container with rest server uses near 5GB RAM on runtime. But in last version 0.4.0 all was working fine, just an upgrade to 0.5.0 caused above problem. I will try to run REST server on my local machine in docker container and check if it is caused by resoruces. Now I am only signaling to you that such problem happened. If you need extra info about my configuration of NLPCraft or anythink, I can share this.

**Comment by aradzinski** [comment]
Should be fixed in 0.5.1. release today.

**Comment by aradzinski** [comment]
Fixed in 0.5.1 release.

**Comment by DankessS** [comment]
Now all works fine. Thanks.
