### ISSUE TITLE
Exception occured while NLPCraft starting due to number limitation

### ISSUE THREAD

**Issue by DankessS** [vic64/nlpcraft#95]
I am using NLPCraft in version 0.6.0. After many deploys my application with use of docker I encountered such exception while NLPCraft is starting (log from nlpcraft-server):

`java.lang.IllegalArgumentException: number can not be greater than 9007199254740992L
        at org.hashids.Hashids.encode(Hashids.java:141) ~[hashids-1.0.3.jar:?]
        at org.nlpcraft.common.util.NCUtils$.genGuid(NCUtils.scala:1210) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.server.user.NCUserManager$$anonfun$addUser0$1.apply$mcVI$sp(NCUserManager.scala:605) ~[nlpcraft-0.6.0.jar:?]
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160) ~[scala-library-2.11.12.jar:?]
        at org.nlpcraft.server.user.NCUserManager$.addUser0(NCUserManager.scala:604) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.server.user.NCUserManager$$anonfun$start$2.apply$mcV$sp(NCUserManager.scala:175) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.server.user.NCUserManager$$anonfun$start$2.apply(NCUserManager.scala:170) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.server.user.NCUserManager$$anonfun$start$2.apply(NCUserManager.scala:170) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.server.sql.NCSql$$anonfun$sqlEx$1.apply(NCSql.scala:419) ~[nlpcraft-0.6.0.jar:?]
        at scala.util.control.Exception$Catch.apply(Exception.scala:103) ~[scala-library-2.11.12.jar:?]
        at org.nlpcraft.server.sql.NCSql$.sqlEx(NCSql.scala:374) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.server.sql.NCSql$.sqlTx(NCSql.scala:341) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.server.sql.NCSql$$anonfun$sql$1.apply(NCSql.scala:323) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.server.tx.NCTxManager$.org$nlpcraft$server$tx$NCTxManager$$startTx0(NCTxManager.scala:229) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.server.tx.NCTxManager$$anonfun$startTx$4.apply(NCTxManager.scala:356) ~[nlpcraft-0.6.0.jar:?]
        at scala.util.control.Exception$Catch.apply(Exception.scala:103) ~[scala-library-2.11.12.jar:?]
        at org.nlpcraft.server.tx.NCTxManager$.startTx(NCTxManager.scala:348) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.server.sql.NCSql$.sql(NCSql.scala:322) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.server.user.NCUserManager$.start(NCUserManager.scala:169) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.server.NCServer$$anonfun$9.apply(NCServer.scala:127) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.server.NCServer$$anonfun$9.apply(NCServer.scala:127) ~[nlpcraft-0.6.0.jar:?]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.12.jar:?]
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) ~[scala-library-2.11.12.jar:?]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.12.jar:?]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.12.jar:?]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.12.jar:?]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.12.jar:?]
`

and there is log from nlpcraft-probe:

`java.lang.ExceptionInInitializerError: null
        at org.nlpcraft.probe.NCProbe$.org$nlpcraft$probe$NCProbe$$startManagers(NCProbe.scala:222) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.probe.NCProbe$$anonfun$1.apply$mcV$sp(NCProbe.scala:110) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.probe.NCProbe$$anonfun$1.apply(NCProbe.scala:110) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.probe.NCProbe$$anonfun$1.apply(NCProbe.scala:110) ~[nlpcraft-0.6.0.jar:?]
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125) ~[scala-library-2.11.12.jar:?]
        at scala.util.control.Exception$Catch$$anonfun$either$1.apply(Exception.scala:125) ~[scala-library-2.11.12.jar:?]
        at scala.util.control.Exception$Catch.apply(Exception.scala:103) ~[scala-library-2.11.12.jar:?]
        at scala.util.control.Exception$Catch.either(Exception.scala:125) ~[scala-library-2.11.12.jar:?]
        at org.nlpcraft.probe.NCProbe$.start(NCProbe.scala:110) [nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.probe.NCProbe$.delayedEndpoint$org$nlpcraft$probe$NCProbe$1(NCProbe.scala:265) [nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.probe.NCProbe$delayedInit$body.apply(NCProbe.scala:63) [nlpcraft-0.6.0.jar:?]
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34) [scala-library-2.11.12.jar:?]
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12) [scala-library-2.11.12.jar:?]
        at scala.App$$anonfun$main$1.apply(App.scala:76) [scala-library-2.11.12.jar:?]
        at scala.App$$anonfun$main$1.apply(App.scala:76) [scala-library-2.11.12.jar:?]
        at scala.collection.immutable.List.foreach(List.scala:392) [scala-library-2.11.12.jar:?]
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35) [scala-library-2.11.12.jar:?]
        at scala.App$class.main(App.scala:76) [scala-library-2.11.12.jar:?]
        at org.nlpcraft.probe.NCProbe$.main(NCProbe.scala:63) [nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.NCStart$.execute(NCStart.scala:94) [nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.NCStart$.delayedEndpoint$org$nlpcraft$NCStart$1(NCStart.scala:99) [nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.NCStart$delayedInit$body.apply(NCStart.scala:42) [nlpcraft-0.6.0.jar:?]
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34) [scala-library-2.11.12.jar:?]
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12) [scala-library-2.11.12.jar:?]
        at scala.App$$anonfun$main$1.apply(App.scala:76) [scala-library-2.11.12.jar:?]
        at scala.App$$anonfun$main$1.apply(App.scala:76) [scala-library-2.11.12.jar:?]
        at scala.collection.immutable.List.foreach(List.scala:392) [scala-library-2.11.12.jar:?]
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35) [scala-library-2.11.12.jar:?]
        at scala.App$class.main(App.scala:76) [scala-library-2.11.12.jar:?]
        at org.nlpcraft.NCStart$.main(NCStart.scala:42) [nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.NCStart.main(NCStart.scala) [nlpcraft-0.6.0.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282) [exec-maven-plugin-1.6.0.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: number can not be greater than 9007199254740992L
        at org.hashids.Hashids.encode(Hashids.java:141) ~[hashids-1.0.3.jar:?]
        at org.nlpcraft.common.util.NCUtils$.genGuid(NCUtils.scala:1210) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.probe.mgrs.conn.NCConnectionManager$.<init>(NCConnectionManager.scala:63) ~[nlpcraft-0.6.0.jar:?]
        at org.nlpcraft.probe.mgrs.conn.NCConnectionManager$.<clinit>(NCConnectionManager.scala) ~[nlpcraft-0.6.0.jar:?]
        ... 37 more
`

I've not deepen into code and analysed this exception, yet. But it looks like some id was overflowed over max value while adding user. Is it somehow connected to Apache Ignite maybe? Maybe I need to remove whole temp files from Apache Ignite, but it's strange that I need to do it manually due to such exception. Please check it.

**Comment by skhdl** [comment]
Thank you. 
We'll investigate it. 

But please take look at 0.7.0.  https://nlpcraft.org/release-notes-0.7.0.html
It will be a long-time support version, all next bugfixes during the significant time will be provided based on it.

**Comment by vic64** [comment]
It's apparently a known problem with Hashids lib. We need to switch our implementation to https://github.com/peet/hashids.java/blob/master/src/HashidsJava/Hashids.java (which apparently fixed that problem). 

I'm adding this to 0.7.1 stream.

**Comment by vic64** [comment]
Fixed in `release`, scheduled for 0.7.1 release.

**Comment by DankessS** [comment]
@vic64 @aradzinski Thank you for the action taken. When do you plan to release version 0.7.1 ?

**Comment by aradzinski** [comment]
@DankessS  0.7.1 release is cut and available.
